image: node:lts-slim

pipelines:  
  branches:
    develop:
    - step:
        name: 'Deployment to Test'
        deployment: test
        script:
          - apt-get update -qq && apt-get install -y -qq lftp
          - npm install
          # - NODE_ENV=production npm run build
          - CI=false npx react-scripts build
          - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnev ./dist ./public_html/flipkoti-test --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ --exclude app/"
          - echo "Your deployment to staging script goes here..."